---
required_packages:
  - firefox
  - tmux
  - vim
  - tilix
  - obsidian
  - keepassxc
  - python-pip
  - python-pylint
  - python-psutil
  - npm
  - nodejs
  - bat 
  - exa
  - grc
  - curlie
  - tree
  - flameshot
  - zsh
  - htop
  - powerline-fonts
  - noto-fonts-emoji
  - papirus-icon-theme
  - mugshot
  - viewnior
  - evince

pentesting_packages:
  # Network
  - nmap
  - gnu-netcat
  - wireshark-qt
  - whois
  - bind
  - tcpdump
  # Web
  - ffuf
  - wfuzz
  - seclists
  # Windows
  - nishang
  - kerbrute
  - impacket
  # Reverse engineering
  - hexedit
  - gdb
  - gef
  - peda
 
firefox_plugins:
  - darkreader
  - foxyproxy-standard
  - wappalyzer
  - ip-address-and-domain-info
  - ublock-origin
  - hacktools
