- name: Obsidian | Create required directories
  file:
    path: "{{ item.opath }}"
    state: directory
  loop:
    - { opath: "{{ ansible_env.HOME }}/Documents/Notes" }
    - { opath: "{{ ansible_env.HOME }}/.config/obsidian" }

- name: Obsidian | Move obsidian.json to config path
  template:
    src: "obsidian.json.j2"
    dest: "{{ ansible_env.HOME }}/.config/obsidian/obsidian.json"

- name: Obsidian | Transfer the configuration files
  copy:
    src: "{{ role_path }}/files/obsidian/"
    dest: "{{ ansible_env.HOME }}/Documents/Notes/.obsidian"
