---
- name: Tilix | Transfer tilix conf file
  copy:
    src: "{{ role_path }}/files/tilix.dconf"
    dest: "/dev/shm/tilix.dconf"

- name: Tilix | Load tilix dconf file 
  shell: dconf load /com/gexperts/Tilix/ < /dev/shm/tilix.dconf
