# Apply wireshark profile for user

- name: Wireshark | Create required directory in user config
  file:
    path: "{{ ansible_env.HOME }}/.config/wireshark/profiles"
    state: directory

- name: Wireshark | Transfer profile to user
  unarchive:
    src: "{{ role_path }}/files/wireshark/wireshark_profile.zip"
    dest: "{{ ansible_env.HOME }}/.config/wireshark/profiles"

- name: Wireshark | Import custom profile instead of default for user  
  copy:
    src: "{{ role_path }}/files/wireshark/recent_common"
    dest: "{{ ansible_env.HOME }}/.config/wireshark/recent_common"

# Apply wireshark profile for root

- name: Wireshark | Create required directory in root config
  file:
    path: "/root/.config/wireshark/profiles"
    state: directory
  become: yes

- name: Wireshark | Transfer profile to root
  unarchive:
    src: "{{ role_path }}/files/wireshark/wireshark_profile.zip"
    dest: "/root/.config/wireshark/profiles"
  become: yes

- name: Wireshark | Import custom profile instead of default for root
  copy:
    src: "{{ role_path }}/files/wireshark/recent_common"
    dest: "/root/.config/wireshark/recent_common"
  become: yes
