- name: Wireshark | Create required directory in user config
  file:
    path: "{{ ansible_env.HOME }}/.config/wireshark/profiles"
    state: directory

- name: Wireshark | Create required directory in root config
  file:
    path: "/root/.config/wireshark/profiles"
    state: directory
  become: yes

- name: Wireshark | Transfer profile to user
  unarchive:
    src: "{{ role_path }}/files/wireshark_profile.zip"
    dest: "{{ ansible_env.HOME }}/.config/wireshark/profiles"

- name: Wireshark | Transfer profile to root
  unarchive:
    src: "{{ role_path }}/files/wireshark_profile.zip"
    dest: "/root/.config/wireshark/profiles"
  become: yes

- name: Wireshark | Import custom profile instead of default for root
  lineinfile:
    path: "/root/.config/wireshark/recent_common"
    regexp: "^gui.last_used_profile:.*$"
    line: "gui.last_used_profile: dolphin_profile"
  become: yes



