---
- name: XFCE | Edit sudoers file temporary
  lineinfile:
    dest: /etc/sudoers
    line: '{{ ansible_env.USER }} ALL=NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: yes
  become_user: root

- name: XFCE | Activate sudo password feedback
  lineinfile:
    dest: /etc/sudoers
    line: "Defaults env_reset,pwfeedback"
    validate: 'visudo -cf %s'
  become: yes
  become_user: root

- name: XFCE | Install dark theme
  command: yay -S plata-theme-bin --noconfirm --noprogressbar --cleanafter

- name: XFCE | Revert changes in sudoers file
  lineinfile:
    dest: /etc/sudoers
    state: absent
    regexp: '^{{ ansible_env.USER }} ALL=NOPASSWD: ALL'
  become: yes
  become_user: root

- name: XFCE | Clone Marwaita icon theme
  git:
    repo: https://github.com/VentGrey/Marwaita-Icons-Remix.git
    dest: /dev/shm/Marwaita-Icons-Remix
    clone: yes

- name: XFCE | Install downloaded icons
  copy:
    src: "/dev/shm/Marwaita-Icons-Remix/"
    dest: "/usr/share/icons"
    remote_src: yes
  become: yes

- name: XFCE | Transfer desktop wallpaper
  copy:
    src: "{{ role_path }}/files/wallpaper.jpg"
    dest: "/usr/share/backgrounds/xfce/wallpaper.jpg"
  become: yes

- name: XFCE | Create htop directory
  file:
    path: "{{ ansible_env.HOME }}/.config/htop"
    state: directory

- name: XFCE | Transfer htop RC file
  copy:
    src: "{{ role_path }}/files/htoprc"
    dest: "{{ ansible_env.HOME }}/.config/htop/htoprc"

- name: XFCE | Delete old xfce configurations of xfce4-panel
  file:
    path: "{{ ansible_env.HOME }}/.config/xfce4/panel"
    state: absent

- name: XFCE | Transfer xfce configurations
  copy:
    src: "{{ role_path }}/files/xfce4"
    dest: "{{ ansible_env.HOME }}/.config/"
    mode: 0755
