---
- name: ZSH | Edit sudoers file temporary
  lineinfile:
    dest: /etc/sudoers
    line: '{{ ansible_env.USER }} ALL=NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: yes
  become_user: root

- name: ZSH | Download oh-my-zsh installation script
  get_url:
    url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh "
    dest: "/dev/shm/ohmyzsh_install.sh"

- name: ZSH | Install oh-my-zsh
  command: sh /dev/shm/ohmyzsh_install.sh --unattended

- name: ZSH | Copy the zshrc file to the default path
  copy:
    src: "{{ role_path }}/files/zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"

- name: ZSH | Make zsh default shell
  shell: "chsh -s $(which zsh) {{ ansible_env.USER }}"
  become: yes

- name: ZSH | Download oh-my-posh installation script
  get_url:
    url: "https://ohmyposh.dev/install.sh"
    dest: "/dev/shm/ohmyposh.sh"

- name: ZSH | Install oh-my-posh
  command: bash /dev/shm/ohmyposh.sh
  become: yes

- name: ZSH | Create oh-my-posh themes directory
  file:
    path: "{{ ansible_env.HOME }}/.poshthemes"
    state: directory

- name: ZSH | Download oh-my-posh theme
  get_url:
    url: "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/catppuccin_mocha.omp.json"
    dest: "{{ ansible_env.HOME }}/.poshthemes/catppuccin_mocha.omp.json"

- name: ZSH | Create directory for NerdFont fonts
  file:
    path: "/usr/share/fonts/Meslo\ LGM\ NF"
    state: directory
  become: yes

- name: ZSH | Install NerdFont (Meslo) for emojie fixes
  unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Meslo.zip"
    dest: "/usr/share/fonts/Meslo\ LGM\ NF"
    remote_src: yes
  become: yes

- name: ZSH | Revert changes in sudoers file
  lineinfile:
    dest: /etc/sudoers
    state: absent
    regexp: '^{{ ansible_env.USER }} ALL=NOPASSWD: ALL'
  become: yes
  become_user: root
